apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ecommerceondapr-statestore
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
# # Uncomment to use SB as pub sub provider 
#  type: pubsub.azure.servicebus.topics
#  version: v1
#  metadata:
#  - name: connectionString
#    value: ""