apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ecommerceondapr-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
# # Uncomment to use SQL as state store provider
#  type: state.sqlserver
#  version: v1
#  metadata:
#    - name: connectionString
#      value: ""
#    - name: actorStateStore
#      value: "true"